# Configuración de MongoDB
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: modulo_asignaturas

  validation:
    enabled: true

# Configuración de logging
logging:
  level:
    cue.edu.co: DEBUG
    org.springframework.data.mongodb: DEBUG

# Configuración del servidor
server:
  port: 8080
