# Configuración de MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=modulo_asignaturas
  
  # Configuración de logging
logging.level.cue.edu.co=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
  
  # Configuración del servidor
server.port=8080
  
  # Configuración de validación
spring.validation.enabled=true