

# MongoDB Atlas - Conexión en la nube
spring.data.mongodb.uri=mongodb+srv://Juan-Arango:1089932748@cluster0.0nla6hv.mongodb.net/modulo_asignaturas?retryWrites=true&w=majority&appName=Cluster0

# JWT - CLAVE SEGURA DE 256 BITS (32+ caracteres)
app.jwtSecret=mySecretKey12345678901234567890123456789012345678901234567890
app.jwtExpirationMs=86400000

# Server
server.port=8080

# Logging
logging.level.co.edu.cue.moduloasignaturas=DEBUG
logging.level.org.springframework.security=DEBUG