
# Nombre de la base de datos
spring.data.mongodb.database=modulo_asignaturas

# URI de conexión a MongoDB local
spring.data.mongodb.uri=mongodb://localhost:27017/modulo_asignaturas

# Configuración opcional para ver logs de Mongo
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
